In [1]:
# On importe les pacakges necessaire

from torchvision import datasets, models, transforms
import torch.nn.functional as F
import matplotlib.pyplot as plt
import torch.optim as optim
import torch.nn as nn
from PIL import Image
import torch
import time
import cv2
import os


In [2]:
# telechargement des données
# Où les données seront stockées

data_path = '/home/cross/Fab2Alex.github.io/Simple_CNN_en_pytorch/'

# Training set
cifar10 = datasets.CIFAR10(data_path, train=True, download=True)
# Val set
cifar10_val = datasets.CIFAR10(data_path, train=False, download=True)

Files already downloaded and verified
Files already downloaded and verified


In [3]:
# chargement les données
# et transformations des données (en tenseur et normalisées)
cifar10 = datasets.CIFAR10(data_path, train=True, download=False,
                          transform=transforms.Compose([
                              transforms.ToTensor(),
                              transforms.Normalize((0.4915, 0.4823, 0.4468),
                                                   (0.2470, 0.2435, 0.2616))
                          ]))

cifar10_val = datasets.CIFAR10(data_path, train=False, download=False,
                          transform=transforms.Compose([
                              transforms.ToTensor(),
                              transforms.Normalize((0.4915, 0.4823, 0.4468),
                                                   (0.2470, 0.2435, 0.2616))
                          ]))

In [4]:
# on prends les données et on les stockent ds une variable en precisant le Batch size
train_loader = torch.utils.data.DataLoader(cifar10, batch_size=64, shuffle = False)
val_loader = torch.utils.data.DataLoader(cifar10_val, batch_size=64, shuffle = False)

In [5]:
class_names = ['airplane','automobile','bird','cat','deer',
               'dog','frog','horse','ship','truck']

In [6]:
# À quoi ressemblent nos données?
for i,data in enumerate(train_loader):
    print(data)
    break

[tensor([[[[-1.0531e+00, -1.3072e+00, -1.1960e+00,  ...,  5.1866e-01,
            4.2339e-01,  3.5989e-01],
          [-1.7358e+00, -1.9899e+00, -1.7041e+00,  ..., -3.7033e-02,
           -1.0054e-01, -5.2909e-02],
          [-1.5930e+00, -1.7358e+00, -1.2119e+00,  ..., -1.1642e-01,
           -8.4663e-02, -2.5931e-01],
          ...,
          [ 1.3125e+00,  1.2014e+00,  1.1537e+00,  ...,  5.5041e-01,
           -1.1008e+00, -1.1484e+00],
          [ 8.6794e-01,  7.5681e-01,  9.6321e-01,  ...,  9.3145e-01,
           -4.4983e-01, -6.7210e-01],
          [ 8.2031e-01,  6.7742e-01,  8.5207e-01,  ...,  1.4395e+00,
            4.0752e-01, -3.7033e-02]],

         [[-9.8219e-01, -1.2399e+00, -1.2077e+00,  ...,  1.4516e-01,
            3.2427e-02,  1.6322e-02],
          [-1.6586e+00, -1.9807e+00, -1.8519e+00,  ..., -5.6346e-01,
           -6.4398e-01, -5.7956e-01],
          [-1.5942e+00, -1.8680e+00, -1.5459e+00,  ..., -6.2788e-01,
           -6.2788e-01, -8.0503e-01],
          ...,
    

In [7]:
# petit rappel de resizing avec pytorch.
y = torch.rand([2,5])
print(y)

tensor([[0.1288, 0.5807, 0.7934, 0.1474, 0.1539],
        [0.7463, 0.6726, 0.8842, 0.6967, 0.4744]])


In [8]:
# le 1 veut dire je veux que tu transforme mon tenseur en tenseur de dimension 1
# le -1 signifie, quelques soit le nombre de colonne et de raws, fait en sorte que ca fonctionne
y.view(1, -1)

tensor([[0.1288, 0.5807, 0.7934, 0.1474, 0.1539, 0.7463, 0.6726, 0.8842, 0.6967,
         0.4744]])

In [9]:
#autre exemple
x = torch.rand([17,5])
print(x)

tensor([[0.1187, 0.0795, 0.3406, 0.2688, 0.4434],
        [0.2191, 0.1615, 0.3506, 0.7800, 0.0529],
        [0.2430, 0.5441, 0.4596, 0.4016, 0.2942],
        [0.4185, 0.1697, 0.5202, 0.4033, 0.3203],
        [0.0815, 0.7495, 0.0012, 0.1376, 0.8433],
        [0.3278, 0.4625, 0.7013, 0.9164, 0.9763],
        [0.9629, 0.8470, 0.3611, 0.3025, 0.8163],
        [0.6460, 0.5118, 0.8193, 0.2249, 0.8175],
        [0.4882, 0.1376, 0.7544, 0.5999, 0.4863],
        [0.9527, 0.1000, 0.7469, 0.0999, 0.0518],
        [0.8223, 0.7987, 0.0907, 0.4766, 0.1714],
        [0.0691, 0.7031, 0.6539, 0.0909, 0.4264],
        [0.6502, 0.4836, 0.6966, 0.1184, 0.0336],
        [0.2146, 0.5537, 0.3411, 0.8942, 0.0402],
        [0.2197, 0.9777, 0.4056, 0.8536, 0.3023],
        [0.8829, 0.2198, 0.2317, 0.4551, 0.3274],
        [0.5367, 0.6431, 0.0293, 0.0907, 0.2548]])


In [10]:
x.view(1, -1)

tensor([[0.1187, 0.0795, 0.3406, 0.2688, 0.4434, 0.2191, 0.1615, 0.3506, 0.7800,
         0.0529, 0.2430, 0.5441, 0.4596, 0.4016, 0.2942, 0.4185, 0.1697, 0.5202,
         0.4033, 0.3203, 0.0815, 0.7495, 0.0012, 0.1376, 0.8433, 0.3278, 0.4625,
         0.7013, 0.9164, 0.9763, 0.9629, 0.8470, 0.3611, 0.3025, 0.8163, 0.6460,
         0.5118, 0.8193, 0.2249, 0.8175, 0.4882, 0.1376, 0.7544, 0.5999, 0.4863,
         0.9527, 0.1000, 0.7469, 0.0999, 0.0518, 0.8223, 0.7987, 0.0907, 0.4766,
         0.1714, 0.0691, 0.7031, 0.6539, 0.0909, 0.4264, 0.6502, 0.4836, 0.6966,
         0.1184, 0.0336, 0.2146, 0.5537, 0.3411, 0.8942, 0.0402, 0.2197, 0.9777,
         0.4056, 0.8536, 0.3023, 0.8829, 0.2198, 0.2317, 0.4551, 0.3274, 0.5367,
         0.6431, 0.0293, 0.0907, 0.2548]])

In [11]:
# connaitre la taille des inputs de sortie des maxpool par exemple avant la FC
# Contrairement aux couches conv dans pyTorch, où l'on a pas besoin de spécifier la taille d'entrée, 
# on doit le spécifier pour les couches entièrement connectées (FC layers).
# Ainsi, lorsque vous définissez la dimension d'entrée de la première couche linéaire, 
# vous devez savoir quelle est la taille des images que vous alimentez
# On créé une classe qui fera cela pour nous

class Print(nn.Module):
    def forward(self, x):
        #print((x.size())
        return x.view(x.size(0),-1)
a = Print()    
    

In [4]:
64*64*3

12288

In [ ]:
class Net(nn.Module):
    def __init__(self):
        super.__init__()
        
        self.Linear = nn.Linear(12288)

In [5]:
# On reprend un reseau de neurones simple mais en y ajoutant des convolutions
class Brain(nn.Module):
    def __init__(self):
        super().__init__()
        # ds cet ordre pr la Conv2D -> channel, filtres (nombre d outputs features) 
        self.conv1 = nn.Conv2d(3, 32, kernel_size=3, padding=1)
        self.act1 = nn.Tanh()
        self.pool1 = nn.MaxPool2d(2)
        # 6 represente le nbre de feature en output
        self.conv2 = nn.Conv2d(32, 6, kernel_size=3, padding=1)
        self.act2 = nn.Tanh()
        self.pool2 = nn.MaxPool2d(2)
        
        self.fc1 = nn.Linear(384, 32)
        self.act3 = nn.Tanh()
        self.fc2 = nn.Linear(32, 10)
        
    def forward(self, x):
        
        out = self.pool1(self.act1(self.conv1(x)))
        out = self.pool2(self.act2(self.conv2(out)))
        
        # D'où vient ce 8*8*6
        # En keras ou tensorflow il exist la methode flatten
        # Mais comment faire en pytorch?
        # source: http://cs231n.github.io/convolutional-networks/#pool
        # https://pytorch.org/docs/stable/nn.html?highlight=maxpool2#torch.nn.Conv2d
        # https://pytorch.org/docs/stable/nn.html?highlight=maxpool2#torch.nn.MaxPool2d
        
        out = a.forward(out)
        print(out.shape)
        print(out.shape[1])
        
        #out = out.view(-1, 8*8*6)
        #a.forward(out)
        out = self.act3(self.fc1(out))
        out = self.fc2(out)
        return out

model = Brain()
print(model)

NameError: name 'nn' is not defined

In [27]:
import datetime

def training_loop(n_epochs, optimizer, model, loss_fn, train_loader):
    for epoch in range(1, n_epochs + 1):
        loss_train = 0.0
        for imgs, labels in train_loader:
            outputs = model(imgs)
            loss = loss_fn(outputs, labels)
            
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            
            loss_train += loss.item()
            
        
        print('{} Epoch {}, Training loss {}'.format(
            datetime.datetime.now(), epoch, float(loss_train)))

In [22]:
model = Brain()
optimizer = optim.SGD(model.parameters(), lr=1e-2)
loss_fn = nn.CrossEntropyLoss()

In [23]:
# training sur fake dataset
#training_loop(n_epochs = 100,optimizer = optimizer,model = model,loss_fn = loss_fn,train_loader = fake_ds)

In [24]:
training_loop(n_epochs = 100,optimizer = optimizer,model = model,loss_fn = loss_fn,train_loader = train_loader)

torch.Size([64, 384])
384
torch.Size([64, 384])
384
torch.Size([64, 384])
384
torch.Size([64, 384])
384
torch.Size([64, 384])
384
torch.Size([64, 384])
384
torch.Size([64, 384])
384
torch.Size([64, 384])
384
torch.Size([64, 384])
384
torch.Size([64, 384])
384
torch.Size([64, 384])
384
torch.Size([64, 384])
384
torch.Size([64, 384])
384
torch.Size([64, 384])
384
torch.Size([64, 384])
384
torch.Size([64, 384])
384
torch.Size([64, 384])
384
torch.Size([64, 384])
384
torch.Size([64, 384])
384
torch.Size([64, 384])
384
torch.Size([64, 384])
384
torch.Size([64, 384])
384
torch.Size([64, 384])
384
torch.Size([64, 384])
384
torch.Size([64, 384])
384
torch.Size([64, 384])
384
torch.Size([64, 384])
384
torch.Size([64, 384])
384
torch.Size([64, 384])
384
torch.Size([64, 384])
384
torch.Size([64, 384])
384
torch.Size([64, 384])
384
torch.Size([64, 384])
384
torch.Size([64, 384])
384
torch.Size([64, 384])
384
torch.Size([64, 384])
384
torch.Size([64, 384])
384
torch.Size([64, 384])
384
torch.Size([

KeyboardInterrupt: 

In [ ]:
for loader in [train_loader, val_loader]:
    correct = 0
    total = 0
    with torch.no_grad():
        for imgs, labels in loader:
            outputs = model(imgs)
            _, predicted = torch.max(outputs, dim=1)
            total += labels.shape[0]
            correct += int((predicted == labels).sum())
    
    print("Accuracy: %f" % (correct / total))

In [11]:
torch.save(model.state_dict(), data_path + 'CIFAR_10.pt')

In [99]:
# faire une prediction sur une image non vue et printer cette prediction
model_entraine = Brain()
model_entraine.load_state_dict(torch.load(data_path + 'CIFAR_10.pt'))


<All keys matched successfully>

### Le même modèle mais avec un resnet block

In [ ]:
# definition dun block Resnet



In [ ]:
# On reprend un reseau de neurones simple mais en y ajoutant des convolutions
class BrainALaResnet(nn.Module):
    def __init__(self):
        super().__init__()
        # ds cet ordre pr la Conv2D -> channel, filtres (nombre d outputs features) 
        self.conv1 = nn.Conv2d(3, 32, kernel_size=3, padding=1)
        self.act1 = nn.Tanh()
        self.pool1 = nn.MaxPool2d(2)
        self.conv2 = nn.Conv2d(32, 8, kernel_size=3, padding=1)
        self.act2 = nn.Tanh()
        self.pool2 = nn.MaxPool2d(2)
        self.fc1 = nn.Linear(8 * 8 * 8, 32)
        self.act3 = nn.Tanh()
        self.fc2 = nn.Linear(32, 10)
        
    def forward(self, x):
        out = self.pool1(self.act1(self.conv1(x)))
        out = self.pool2(self.act2(self.conv2(out)))
        out = out.view(-1, 8 * 8 * 8)
        out = self.act3(self.fc1(out))
        out = self.fc2(out)
        return out

model = Brain()
print(model)

In [ ]:
# rajouter: 
# regularization
# dropout
# batch normalization
# data augmentation
# transfer learning


In [ ]:
# resnet Block
# data_augmentation
# object_detection    